### ISSUE TITLE
[USER STORY] PyCharm Setup

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#10]
As a **developer**, I can **set up PyCharm** so that **I can create, edit, and test my app locally**.

### Acceptance Criteria
- PyCharm project created
- PyCharm project linked to GitHub
- Django installed and app created
- Necessary environment variables set

### Tasks
- [x] File > Open > select local GitHub directory
- [x] In PyCharm's Terminal, install and extract the necessary libraries
  - `pip3 install django==4.2.10`
  - `pip3 install gunicorn`
  - `pip3 freeze local > requirements.txt`
- [x] In PyCharm's Terminal, create the Django project and app
  - `django-admin startproject nutriforce .`
  - `python3 manage.py startapp nutriforce_app`
- [x] Update the settings.py file with the following
  - Add `import os` to the file imports
  - Add `import dj_database_url` to the file imports
  - Under the file imports, add `development = os.environ.get('DEVELOPMENT', False)`
  - Change the SECRET_KEY line to `SECRET_KEY = os.environ.get('SECRET_KEY', '')`
  - Change `DEBUG = True` to `DEBUG = development`
  - Add the app name into the INSTALLED_APPS section
  - In the ALLOWED_HOSTS section, write an if statement to check the development status
    - `if development:`
       `    ALLOWED_HOSTS = ['127.0.0.1']`
       `else:`
       `    ALLOWED_HOSTS = [os.environ.get('HEROKU_HOSTNAME')]`
- [x] Create a Procfile file in the main folder for the app
  - Right-click on the main folder (ci_project5)
  - New > File > Procfile > Enter key
  - Add `web: gunicorn codestar.wsgi` to the file and save
- [x] Run the server to ensure the initial app is set up correctly
  - `python3 manage.py runserver`
- [x] Environment variables set in PyCharm > Settings > Tools > Terminal
  - Open the Environment variables window with the small paper icon on the right
  - Add the name "DEVELOPMENT" with the value "True"
  - Add the name "HEROKU_HOSTNAME" with the value of your Heroku app URL excluding the first https:// and the last /
    - Go to your Heroku app and click Open app in the upper right to get the URL
  - Add the name "SECRET_KEY" with the value of your auto-generated Django secret key added to Heroku
- [x] Commit the changes to GitHub

### Linked EPIC
- #6

**Comment by crazycooky77** [comment]
Completed local PyCharm setup
