### ISSUE TITLE
[USER STORY] Account Creation

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#15]
As a **user**, I can **create an account** so that **I can save and access my data, and make purchases**.

### Acceptance Criteria
- Create an account with the following options:
    - Email address
    - Password

### Tasks
- [x] Account creation feature
- [x] Encrypt passwords
- [x] Check for existing accounts
- [x] Set minimum password requirements

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
Account creation feature functional and styled
