### ISSUE TITLE
[USER STORY] Account Editing

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#16]
As a **user**, I can **edit my account** so that **I can ensure all my data is fully up-to-date**.

### Acceptance Criteria
- Edit email address
- Edit password
- Add saved address
- Edit saved address

### Tasks
- [x] Edit email address feature
    - Check if account with the email already exists
- [x] Edit password feature
    - Ensure minimum password requirements are met
- [x] Add saved address to account
- [x] Edit saved addresses in account

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
Functions to edit all account options successfully added. Edit email, password, add addresses and edit addresses all confirmed as working.
