### ISSUE TITLE
[USER STORY] Account Deletion

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#17]
As a **user**, I can **delete my account** so that **I am in full control of my data**.

### Acceptance Criteria
- Delete account option

### Tasks
- [x] Account deletion by user
- [x] Warning to the user
- [x] Delete corresponding Addresses from model
- [x] Delete corresponding Purchases from model
- [x] Keep "DELETED" Address IDs for Orders model
- [x] Keep "DELETED" User IDs for Orders model

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
Complete - tested, and related information is replaced accordingly, with deleted data, while retaining the actual order.
