### ISSUE TITLE
[USER STORY] Password Reset

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#18]
As a **user**, I can **reset the password to my account** so that **I can regain access to it, if I forget it**.

### Acceptance Criteria
- Forgot password option

### Tasks
- [x] Forgot password button
- [x] Email to user with link to reset it
- [x] Ensure minimum requirements are met
- [x] Encrypt passwords

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
Password reset functionality implemented
