### ISSUE TITLE
[USER STORY] User Profile Page

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#19]
As a **user**, I can **view my user profile** so that **I can review all my data and purchases**.

### Acceptance Criteria
- User profile view
- View of account details
    - Email address
    - Saved Addresses
- Order history

### Tasks
- [x] Profile page creation
- [x] Saved Addresses view
- [x] Order History view

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
all account and order details added to profile page views
