### ISSUE TITLE
[USER STORY] Social Media Signup

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#20]
As a **user**, I can **sign up and in to the site via Social Media accounts** so that **I don't have to create and remember a separate account**.

### Acceptance Criteria
- Social media sign-up options
- Social media login

### Tasks
- [ ] Apple ID sign-up
- [ ] Facebook sign-up
- [ ] Google sign-up
- [ ] Apple ID login
- [ ] Facebook login
- [ ] Google login

### Linked EPIC
- #1

**Comment by crazycooky77** [comment]
User Story moved to release 1.1 - Set to wont-have for 1.0.
