### ISSUE TITLE
[USER STORY] Add to Cart

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#22]
As a **user**, I can **add products to my cart** so that **I can save and access them for purchasing**.

### Acceptance Criteria
- Add to Cart function

### Tasks
- [x] Create Add to Cart option
    - Cart content saved in Browser cookies if not signed in
    - Cart content saved to account if signed in
- [x] Do not allow to add to cart if item is out of stock
- [x] Restrict amount of items that can be added, depending on stock

### Linked EPIC
- #5

**Comment by crazycooky77** [comment]
Cart functions complete, including merging logged out cart with logged in cart, if applicable.
