### ISSUE TITLE
[USER STORY] Edit Cart

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#23]
As a **user**, I can **edit the contents in my cart** so that **I can update the number of items per product, if I want to buy more or less of a product**.

### Acceptance Criteria
- Ability to edit the number of items per Product in the cart

### Tasks
- [x] View Cart page
- [x] Visible field for number of items per Product in Cart
- [x] Left/right arrow by the number to increase/decrease the number of items
- [x] Restrict increasing the number of items depending on stock
- [x] "Update Cart" button

### Linked EPIC
- #5

**Comment by crazycooky77** [comment]
Cart editing features completed. Additionally added option to delete a single item completely from the cart
