### ISSUE TITLE
[USER STORY] Complete Purchase

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#30]
As a **user**, I can **purchase the items in my cart** so that **I can order and receive the items I want from the store**.

### Acceptance Criteria
- Checkout as guest
- Checkout when signed in
- Different payment options
- Address options
- Note to Seller

### Tasks
- [x] Guest checkout
- [x] Account checkout
- [x] Check stock count at checkout, and update database stock count
- [x] Stripe payment
- [x] Billing address
- [x] Shipping address (IE only)
- [x] Note to shop/seller
- [x] Completed purchase page
- [x] Email to user upon completed purchase
- [x] Email to admin upon completed purchase
- [x] Cancel checkout option

### Linked EPIC
- #5

**Comment by crazycooky77** [comment]
Completed all tasks for checkout process
