### ISSUE TITLE
[USER STORY] Automated Testing

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#32]
As a **developer**, I can **build and run automated tests** so that **I can ensure all website functions work correctly, without having to manually test everything**.

### Acceptance Criteria
- List all classes/functions from forms.py and views.py
- Create a test file for each (forms and views)
- Write tests for each
- Run python coverage to check where there are missing automated tests

### Tasks
- [ ] List all classes/functions from forms and views
- [ ] Create a test file each for forms and views
- [ ] Write tests for all classes and functions
- [ ] Aim for 100% coverage from python coverage

### Linked EPIC
- #4

**Comment by crazycooky77** [comment]
User Story moved to release 1.1 - Set to wont-have for 1.0.
