### ISSUE TITLE
[USER STORY] Mobile CSS

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#40]
As a **user**, I can **properly view the website on smaller screens** so that **I can interact with it and make purchases, even from my phone**.

### Acceptance Criteria
- CSS on all pages modified for smaller screens
- JavaScript initially made for desktops also works on smaller screens/mobile devices

### Tasks
- [x] Update CSS for smallest screen size
- [x] If needed, update CSS for medium size screens
- [x] Ensure large displays still show the styling properly
- [x] Initial/minor testing of JS features on mobiles

### Linked EPIC
- #4

**Comment by crazycooky77** [comment]
All mobile sizing styling completed with initial minor testing. Implemented standard, 1100px, 800px, and 500px max-widths. Styling works well down to 310px.
