### ISSUE TITLE
[USER STORY] Newsletter

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#42]
As a **user**, I can **sign up to a newsletter** so that **I can be notified of special promotions or new products without having to look for them**.

### Acceptance Criteria
- Database model for users/email addresses subscribed
- Newsletter signup link
- Unsubscribe link in user account
- Unsubscribe link in newsletter
- Confirmation email on signup

### Tasks
- [x] Database model for users/email addresses subscribed
- [x] Newsletter signup link
- [x] Unsubscribe link in user account
- [x] Unsubscribe link in newsletter
- [x] Confirmation email on signup

**Comment by crazycooky77** [comment]
All newsletter features implemented.
