### ISSUE TITLE
[USER STORY] GitHub Setup

### ISSUE THREAD

**Issue by crazycooky77** [crazycooky77/ci_project5#7]
As a **developer**, I can **set up GitHub to host all my Issues and code** so that **I can track tasks and progress, as well as have proper version control**.

### Acceptance Criteria
- GitHub repository created with CI template
- Issue templates created
- Issues created and organised
- Repository set up in GitHub Desktop

### Tasks
- [x] Clone [Code Institute](https://github.com/Code-Institute-Org/ci-full-template) template
  - Use this template
  - Create a [new repository](https://github.com/crazycooky77/ci_project5)
- [x] Create [new project board](https://github.com/users/crazycooky77/projects/2)
  - Projects > Link a project > New project
- [x] Create Issues templates for EPICs, User Story, Bugs, and Feature Requests
  - Settings > General > Features > Set up templates
  - Add template > Custom template
  - Preview and edit > Propose changes
  - Commit changes to main branch
- [x] Create Labels
  - Issues > Labels > New label
- [x] Create EPICs and user stories to plan out necessary features/work for the initial launch of the app
  - Issues > New issue
- [x] Link all [Issues](https://github.com/crazycooky77/ci_project5/issues) to the [project board](https://github.com/users/crazycooky77/projects/2)
- [x] Code > Open with GitHub Desktop > Clone

### Linked EPIC
- #6

**Comment by crazycooky77** [comment]
GitHub setup complete, including all initial User Stories
